### ISSUE TITLE
admin-panel

### ISSUE THREAD

**Issue by ali-7** [FACG5/gsgca-project#1]
Code:
- [x] Admin panel routes
- [x] Admin panel pages
- [x] Admin panel database schema
- [x] Admin panel database queries
